folder_structure: planche_${MAPSHEET}/${IMAGE_NAME}.tif
workspace_directory: data/walousupdate/fastapi
output_directory: data/walousupdate/fastapi/output
output_filename: WAL_OCS_XXXX


initialization:
  maillage_filepath: data/maillage/2019/SPW_2019_MAILLAGE.shp

preprocessing:
  ortho_directory: input/ORTHOS_2019/TIFF
  mns_filepath: input/MNS_ORTHOS_2019/TIFF/RELIEF_WALLONIE_MNS_ORTHOS_2019.tif
  mnt_filepath: input/MNT_2013_2014/TIFF/RELIEF_WALLONIE_MNT_2013_2014.tif

inference:
  overlap: 12

resampling:
  skip: false
  upscale_factor_x: null
  upscale_factor_y: null

erosion:
  skip: false
  threshold: 16
  connectedness: 8

fusion:
  skip: true
  sources:
    railway:
      shapes_filepath: /data/walous/WP2_Squelette/rails/railway_IGN.shp
      buffer: 2
      filter_on_labels: [1, 5, 8, 9]
      main_label: 3
    watercourse:
      shapes_filepath: /data/walous/WP2_Squelette/eau/IGN_WatercourseSurface.shp
      buffer: 0
      filter_on_labels: [1, 3, 8, 9]
      main_label: 5
    building:
      shapes_filepath: /data/walous/WP2_Squelette/batiments/PICC_BATIMENTS.shp
      buffer: 0
      filter_on_labels: [8, 9]
      main_label: 2

compulsion:
  skip: true

comparison:
  skip: false
  previous_ocs_filepath: data/WAL_OCS_2018/WAL_OCS_2018.tif
  only_main_label: true
  output_format: 2

cropping:
  skip: true
  all_touched: true

reprojection:
  skip: true
  to_srs: EPSG:3812
  coordinate_transform: +proj=pipeline +step +inv +proj=lcc +lat_0=90 +lon_0=4.36748666666667 +lat_1=51.1666672333333 +lat_2=49.8333339 +x_0=150000.013 +y_0=5400088.438 +ellps=intl +step +proj=hgridshift +grids=bd72lb72_etrs89lb08.gsb +step +proj=lcc +lat_0=50.797815 +lon_0=4.35921583333333 +lat_1=49.8333333333333 +lat_2=51.1666666666667 +x_0=649328 +y_0=665262 +ellps=GRS80
  target_extents: "540000.000 520000.000 800000.000 670000.000"
  target_resolution: "1 1"
  target_aligned_pixels: true

compression:
  skip : false
  method: LZW

vectorization:
  skip: true
  connectedness: 8
  output_format: "GPKG"
  output_file_extension: ".gpkg"
